# Generated by Django 6.0.2 on 2026-02-20 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original / strike-through price for sale display', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Option name, e.g. "Size" or "Color"', max_length=100)),
                ('value', models.CharField(help_text='Option value, e.g. "XL" or "Red"', max_length=100)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Added to the base product price. Use negative values for discounted variants.', max_digits=8)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'db_table': 'product_variants',
                'ordering': ['name', 'order', 'value'],
                'unique_together': {('product', 'name', 'value')},
            },
        ),
    ]
